THRESHOLD=94000
LIMIT=5000
INDEX=0
EXTRA=""
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16_106X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer20UL16_106X_Data_Leptons/ > CheckFiles_Summer20UL16_106X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16APV_106X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer20UL16APV_106X_Data_Leptons/ > CheckFiles_Summer20UL16APV_106X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer20UL17_106X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer20UL17_106X_Data_Leptons/ > CheckFiles_Summer20UL17_106X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer20UL18_106X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer20UL18_106X_Data_Leptons/ > CheckFiles_Summer20UL18_106X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer22_130X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer22_130X_Data_Leptons/ > CheckFiles_Summer22_130X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer22EE_130X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer22EE_130X_Data_Leptons/ > CheckFiles_Summer22EE_130X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer23_130X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer23_130X_Data_Leptons/ > CheckFiles_Summer23_130X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer23BPix_130X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer23BPix_130X_Data_Leptons/ > CheckFiles_Summer23BPix_130X_Data_Leptons_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py ${EXTRA} -l ${LIMIT} -t ${THRESHOLD} -d /home/${USER}/CMSSW_13_3_1/src/SUSYCascades/Summer24_130X_Data_Leptons/ -o /ospool/cms-user/${USER}/NTUPLES/Processing/Summer24_130X_Data_Leptons/ > CheckFiles_Summer24_130X_Data_Leptons_${INDEX}.debug 2>&1 &
