THRESHOLD=94000
LIMIT=5000
INDEX=0
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16APV_106X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL16APV_106X/ > CheckFiles_Summer20UL16APV_106X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16_106X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL16_106X/ > CheckFiles_Summer20UL16_106X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL17_106X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL17_106X/ > CheckFiles_Summer20UL17_106X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL18_106X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL18_106X/ > CheckFiles_Summer20UL18_106X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer22_130X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer22_130X/ > CheckFiles_Summer22_130X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer22EE_130X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer22EE_130X/ > CheckFiles_Summer22EE_130X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer23_130X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer23_130X/ > CheckFiles_Summer23_130X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer23BPix_130X_HISTS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer23BPix_130X/ > CheckFiles_Summer23BPix_130X_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16APV_106X_SMS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL16APV_106X_SMS_HISTS/ > CheckFiles_Summer20UL16APV_106X_SMS_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL16_106X_SMS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL16_106X_SMS_HISTS/ > CheckFiles_Summer20UL16_106X_SMS_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL17_106X_SMS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL17_106X_SMS_HISTS/ > CheckFiles_Summer20UL17_106X_SMS_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -a -l ${LIMIT} -t ${THRESHOLD} -d /home/zflowers/CMSSW_13_3_1/src/SUSYCascades/Summer20UL18_106X_SMS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer20UL18_106X_SMS_HISTS/ > CheckFiles_Summer20UL18_106X_SMS_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -d Summer23BPix_130X_Cascades/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer23BPix_130X_Cascades/ -l ${LIMIT} -t ${THRESHOLD} > CheckFiles_Summer23BPix_130X_Cascades_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -d Summer22_130X_Cascades/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer22_130X_Cascades/ -l ${LIMIT} -t ${THRESHOLD} -w -c > CheckFiles_Summer22_130X_Cascades_${INDEX}.debug 2>&1 &
nohup python3 python/CheckFiles.py -d Summer22_130X_SMS/ -o /ospool/cms-user/zflowers/HISTS/Processing/Summer22_130X_SMS/ -l ${LIMIT} -t ${THRESHOLD} -w -c > CheckFiles_Summer22_130X_SMS_${INDEX}.debug 2>&1 &
