# nohup ./scripts/xrdcp_helper.sh > xrdcp_helper.debug 2>&1 &
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23BPix_130X_Cascades/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23BPix_130X_Cascades/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22_130X_Cascades/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22_130X_Cascades/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16_106X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16_106X_SMS/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16APV_106X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16APV_106X_SMS/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL17_106X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL17_106X_SMS/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL18_106X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL18_106X_SMS/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22_130X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22_130X_SMS/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22EE_130X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22EE_130X_SMS/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23_130X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23_130X_SMS/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23BPix_130X_SMS/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23BPix_130X_SMS/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16_106X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16_106X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16APV_106X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16APV_106X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL17_106X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL17_106X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL18_106X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL18_106X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22_130X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22_130X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22EE_130X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22EE_130X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23_130X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23_130X_Data/
xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23BPix_130X_Data/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23BPix_130X_Data/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16_106X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16_106X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL16APV_106X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL16APV_106X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL17_106X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL17_106X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer20UL18_106X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer20UL18_106X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22_130X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22_130X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer22EE_130X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer22EE_130X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23_130X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23_130X/
#xrdcp --parallel 4 -f /local-scratch/zflowers/NTUPLES/HADD/Summer23BPix_130X/*.root root://cmseos.fnal.gov//store/user/lpcsusylep/NTUPLES_Cascades_v7/Summer23BPix_130X/
